version update, activator plugin ++

diff --git a/plugins/activator/install b/plugins/activator/install
--- a/plugins/activator/install
+++ b/plugins/activator/install
@@ -1,10 +1,21 @@
 AHH_PATH=$1
 PLUGIN_NAME=$2
 PLUGIN_PATH=$3
-WORK_PATH=$AHH_PATH/work
+WORK_PATH=$4
 echo "ahh :" $AHH_PATH
 echo "name:" $PLUGIN_NAME
 echo "path:" $PLUGIN_PATH
+echo "work:" $WORK_PATH
 
 echo "install here..."
+
+cat $PLUGIN_PATH/url | xargs -IX wget X -O $WORK_PATH/arch.zip || { echo "failed"; exit; }
+unzip -f $WORK_PATH/arch.zip -d $WORK_PATH || { echo "failed"; exit; }
+
+ln -s $WORK_PATH/sbt/bin/sbt ~/bin/sbt/
+
+ls -R $WORK_PATH
+
+echo "installed..."
+
 
